import { ft } from "@/lib/units";
import type { SceneObject, SourceCitation, VenueTwin, ShowPlacement } from "../types";

const sources: SourceCitation[] = [
  {
    id: "spec-tf-plan",
    fileName: "SpectrumCenter_EndStage_TechPack.pdf",
    pageOrSheet: "TF-01",
    revision: "Rev C",
    date: "2025-08-04",
    authority: "VENUE_ISSUED",
    confidence: "CALIBRATED_PLANNING",
    originalText:
      "End-stage floor 85′ × 200′, center court at floor midpoint. Low steel 107′ AFF, high steel 130′ AFF.",
  },
  {
    id: "spec-rig-cap",
    fileName: "SpectrumCenter_RiggingCapacities.pdf",
    pageOrSheet: "R-02",
    revision: "Rev B",
    date: "2024-05-10",
    authority: "VENUE_ISSUED",
    confidence: "ENGINEERING_CONFIRMATION_REQUIRED",
    originalText:
      "Total end-stage rigging capacity reference 150,000 lb. Marked span reference maximum 5,000 lb. Max load angle 30° from vertical.",
    notes: "Reference values — engineering confirmation required per show.",
  },
  {
    id: "spec-drt-place",
    fileName: "DRT_Spectrum_Placement_v0.2.pdf",
    pageOrSheet: "P-01",
    revision: "v0.2",
    date: "2026-12-01",
    authority: "TOUR_ISSUED",
    confidence: "CALIBRATED_PLANNING",
    originalText:
      "Show origin 76′ upstage from center court. Nominal deck side remainder 3′ 6″ per side. Backstage clearance ~27′ 9″.",
  },
];

// Scene frame: origin at floor center, +Z upstage, +X SL, +Y up.
const floorW = ft(85);
const floorD = ft(200);

const objects: SceneObject[] = [
  {
    id: "spec-floor",
    kind: "venue-floor",
    label: "Event Floor",
    layer: "venue-shell",
    origin: "venue",
    position: { x: 0, y: 0, z: 0 },
    geometry: { type: "plane", size: { w: floorW, d: floorD } },
    color: "floor",
    confidence: "CALIBRATED_PLANNING",
    authority: "VENUE_ISSUED",
    sourceIds: ["spec-tf-plan"],
    dims: "85′ × 200′",
  },
  {
    id: "spec-court",
    kind: "court-marker",
    label: "Center Court (anchor)",
    layer: "venue-shell",
    origin: "venue",
    position: { x: 0, y: 0.01, z: 0 },
    geometry: { type: "marker", radius: ft(6) },
    color: "accent",
    confidence: "VERIFIED",
    authority: "VENUE_ISSUED",
    sourceIds: ["spec-tf-plan"],
    dims: "Floor midpoint · anchor for placement",
  },
  {
    id: "spec-bowl-lower",
    kind: "bowl-mass",
    label: "Lower Bowl",
    layer: "venue-bowl",
    origin: "venue",
    position: { x: 0, y: ft(12), z: 0 },
    geometry: { type: "box", size: { x: floorW + ft(60), y: ft(24), z: floorD + ft(80) } },
    color: "bowl-lower",
    confidence: "APPROXIMATE_PLANNING",
    authority: "INFERRED",
    sourceIds: ["spec-tf-plan"],
    dims: "Abstract mass",
    notes: "Massing only — not seating manifest.",
  },
  {
    id: "spec-bowl-club",
    kind: "bowl-mass",
    label: "Club Level",
    layer: "venue-bowl",
    origin: "venue",
    position: { x: 0, y: ft(42), z: 0 },
    geometry: { type: "box", size: { x: floorW + ft(90), y: ft(14), z: floorD + ft(110) } },
    color: "bowl-club",
    confidence: "APPROXIMATE_PLANNING",
    authority: "INFERRED",
    sourceIds: ["spec-tf-plan"],
  },
  {
    id: "spec-bowl-upper",
    kind: "bowl-mass",
    label: "Upper Bowl",
    layer: "venue-bowl",
    origin: "venue",
    position: { x: 0, y: ft(68), z: 0 },
    geometry: { type: "box", size: { x: floorW + ft(120), y: ft(30), z: floorD + ft(140) } },
    color: "bowl-upper",
    confidence: "APPROXIMATE_PLANNING",
    authority: "INFERRED",
    sourceIds: ["spec-tf-plan"],
  },
  {
    id: "spec-low-steel",
    kind: "grid-plane",
    label: "Low Steel Reference",
    layer: "venue-rigging",
    origin: "venue",
    position: { x: 0, y: ft(107), z: 0 },
    geometry: { type: "plane", size: { w: floorW + ft(40), d: floorD + ft(40) } },
    color: "grid",
    confidence: "CALIBRATED_PLANNING",
    authority: "VENUE_ISSUED",
    sourceIds: ["spec-tf-plan", "spec-rig-cap"],
    dims: "107′ AFF",
    notes: "Venue reference — engineering confirmation required.",
  },
  {
    id: "spec-high-steel",
    kind: "grid-plane",
    label: "High Steel Reference",
    layer: "venue-rigging",
    origin: "venue",
    position: { x: 0, y: ft(130), z: 0 },
    geometry: { type: "plane", size: { w: floorW + ft(60), d: floorD + ft(60) } },
    color: "grid-soft",
    confidence: "CALIBRATED_PLANNING",
    authority: "VENUE_ISSUED",
    sourceIds: ["spec-tf-plan"],
    dims: "130′ AFF",
  },
  {
    id: "spec-scoreboard",
    kind: "scoreboard",
    label: "Scoreboard Reference Mass",
    layer: "venue-rigging",
    origin: "venue",
    position: { x: 0, y: ft(88), z: 0 },
    geometry: { type: "box", size: { x: ft(40), y: ft(18), z: ft(40) } },
    color: "scoreboard",
    confidence: "APPROXIMATE_PLANNING",
    authority: "INFERRED",
    sourceIds: ["spec-tf-plan"],
    dims: "Reference envelope only",
    notes: "Assumed centered — confirm with venue.",
  },
  {
    id: "spec-stage-boundary",
    kind: "stage-boundary",
    label: "Stage-End Boundary",
    layer: "venue-shell",
    origin: "venue",
    // Stage end is upstage side (+Z end of floor)
    position: { x: 0, y: 0.02, z: floorD / 2 - ft(0, 6) },
    geometry: { type: "plane", size: { w: floorW, d: ft(1) } },
    color: "boundary",
    confidence: "CALIBRATED_PLANNING",
    authority: "VENUE_ISSUED",
    sourceIds: ["spec-tf-plan"],
  },
  {
    id: "spec-dock",
    kind: "dock-zone",
    label: "Loading Dock Zone",
    layer: "venue-ops",
    origin: "venue",
    position: { x: floorW / 2 + ft(18), y: 0.02, z: floorD / 2 + ft(12) },
    geometry: { type: "plane", size: { w: ft(30), d: ft(50) } },
    color: "ops",
    confidence: "APPROXIMATE_PLANNING",
    authority: "PRIOR_SHOW_REFERENCE",
    sourceIds: ["spec-tf-plan"],
    dims: "Reference position",
  },
  {
    id: "spec-boh",
    kind: "boh-zone",
    label: "BOH / Backstage",
    layer: "venue-ops",
    origin: "venue",
    position: { x: 0, y: 0.02, z: floorD / 2 + ft(24) },
    geometry: { type: "plane", size: { w: floorW + ft(40), d: ft(40) } },
    color: "ops-soft",
    confidence: "APPROXIMATE_PLANNING",
    authority: "PRIOR_SHOW_REFERENCE",
    sourceIds: ["spec-tf-plan"],
  },
];

export const spectrumCenter: VenueTwin = {
  id: "spectrum-center",
  name: "Spectrum Center",
  city: "Charlotte, NC",
  revision: "Rev C · 2025-08-04",
  floor: { widthFt: 85, depthFt: 200 },
  lowSteelFt: 107,
  highSteelFt: 130,
  riggingCapLb: 150000,
  markedSpanMaxLb: 5000,
  maxLoadAngleDeg: 30,
  disclaimer:
    "Venue reference values shown are for planning only. Every rigging point, load, span and angle requires engineering confirmation per show. This system does not replace venue rigging approval, engineering, fire marshal, life safety, seating manifest or ADA review.",
  sources,
  objects,
};

// Show origin: 76 ft upstage from center court. Upstage = +Z.
export const spectrumPlacement: ShowPlacement = {
  id: "drt-at-spectrum",
  venueId: "spectrum-center",
  packageId: "drt-2027-spring",
  revision: "v0.2 · 2026-12-01",
  showOrigin: { x: 0, y: 0, z: ft(76) },
  showRotationY: Math.PI, // face downstage (toward center court / audience)
  notes:
    "B-stage center locks to center court. Nominal deck side remainder 3′ 6″ per side. Plan-derived backstage clearance ≈ 27′ 9″.",
  adaptations: [
    {
      id: "a1",
      title: "B-stage center anchored to center court",
      detail: "Show origin offset 76′ upstage places B-stage local center on center court.",
      sourceIds: ["spec-drt-place"],
    },
    {
      id: "a2",
      title: "Deck side remainder 3′ 6″",
      detail: "78′ deck within 85′ floor width leaves 3′ 6″ each side — confirm barricade path.",
      sourceIds: ["spec-drt-place", "spec-tf-plan"],
    },
  ],
  conflicts: [
    {
      id: "c1",
      title: "Backstage clearance tight",
      severity: "warn",
      detail:
        "Plan-derived ~27′ 9″ backstage clearance requires PROD/TM confirmation for case pack and quick-change lanes.",
      sourceIds: ["spec-drt-place"],
    },
    {
      id: "c2",
      title: "Scoreboard envelope vs monolith top",
      severity: "info",
      detail:
        "Monolith vertex 35′ 4″ AFD sits ~41′ 4″ AFF; scoreboard reference bottom assumed higher — confirm actual scoreboard trim.",
      sourceIds: ["spec-rig-cap"],
    },
  ],
  actions: [
    {
      id: "act1",
      title: "Confirm marked span points along monolith load path",
      owner: "RIGGING",
      status: "in-progress",
    },
    {
      id: "act2",
      title: "Verify dock-to-stage forklift path with venue ops",
      owner: "PM",
      status: "open",
    },
    {
      id: "act3",
      title: "Seating impact review for center-court B-stage",
      owner: "VENUE",
      status: "open",
    },
  ],
  sources,
};
