import type { TourShow } from "../types";

// 19-show Spring 2027 DRT Tour seed.
export const tourShows: TourShow[] = [
  {
    id: "s01",
    city: "Charlotte, NC",
    venueName: "Spectrum Center",
    venueSlug: "spectrum-center",
    date: "2027-03-04",
    fidelity: "PILOT",
    sourceScore: 72,
    riggingStatus: "IN_REVIEW",
    logisticsStatus: "SCHEDULED",
    pmAction: "Confirm dock schedule",
    tmAction: "Bus call pending",
    lastRevision: "2026-12-01",
  },
  {
    id: "s02",
    city: "Raleigh, NC",
    venueName: "Lenovo Center",
    date: "2027-03-06",
    fidelity: "SEED",
    sourceScore: 34,
    riggingStatus: "NOT_STARTED",
    logisticsStatus: "PENDING",
    pmAction: "Request tech pack",
    lastRevision: "2026-11-20",
  },
  {
    id: "s03",
    city: "Atlanta, GA",
    venueName: "State Farm Arena",
    date: "2027-03-08",
    fidelity: "SEED",
    sourceScore: 41,
    riggingStatus: "NOT_STARTED",
    logisticsStatus: "PENDING",
    pmAction: "Kickoff call",
    lastRevision: "2026-11-18",
  },
  {
    id: "s04",
    city: "Nashville, TN",
    venueName: "Bridgestone Arena",
    date: "2027-03-11",
    fidelity: "SEED",
    sourceScore: 38,
    riggingStatus: "NOT_STARTED",
    logisticsStatus: "PENDING",
    lastRevision: "2026-11-14",
  },
  {
    id: "s05",
    city: "Memphis, TN",
    venueName: "FedExForum",
    date: "2027-03-13",
    fidelity: "SEED",
    sourceScore: 30,
    riggingStatus: "NOT_STARTED",
    logisticsStatus: "PENDING",
    lastRevision: "2026-11-10",
  },
  {
    id: "s06",
    city: "St. Louis, MO",
    venueName: "Enterprise Center",
    date: "2027-03-15",
    fidelity: "SEED",
    sourceScore: 28,
    riggingStatus: "NOT_STARTED",
    logisticsStatus: "PENDING",
    lastRevision: "2026-11-09",
  },
  {
    id: "s07",
    city: "Kansas City, MO",
    venueName: "T-Mobile Center",
    date: "2027-03-17",
    fidelity: "SEED",
    sourceScore: 26,
    riggingStatus: "NOT_STARTED",
    logisticsStatus: "PENDING",
    lastRevision: "2026-11-08",
  },
  {
    id: "s08",
    city: "Tulsa, OK",
    venueName: "BOK Center",
    venueSlug: "bok-center",
    date: "2027-03-19",
    fidelity: "SEED",
    sourceScore: 22,
    riggingStatus: "NOT_STARTED",
    logisticsStatus: "PENDING",
    pmAction: "Request tech pack",
    lastRevision: "2026-11-07",
  },
  {
    id: "s09",
    city: "Dallas, TX",
    venueName: "American Airlines Center",
    date: "2027-03-21",
    fidelity: "SEED",
    sourceScore: 44,
    riggingStatus: "NOT_STARTED",
    logisticsStatus: "PENDING",
    lastRevision: "2026-11-05",
  },
  {
    id: "s10",
    city: "Houston, TX",
    venueName: "Toyota Center",
    date: "2027-03-24",
    fidelity: "SEED",
    sourceScore: 36,
    riggingStatus: "NOT_STARTED",
    logisticsStatus: "PENDING",
    lastRevision: "2026-11-03",
  },
  {
    id: "s11",
    city: "San Antonio, TX",
    venueName: "Frost Bank Center",
    date: "2027-03-26",
    fidelity: "SEED",
    sourceScore: 20,
    riggingStatus: "NOT_STARTED",
    logisticsStatus: "PENDING",
    lastRevision: "2026-10-30",
  },
  {
    id: "s12",
    city: "Denver, CO",
    venueName: "Ball Arena",
    date: "2027-03-29",
    fidelity: "SEED",
    sourceScore: 32,
    riggingStatus: "NOT_STARTED",
    logisticsStatus: "PENDING",
    lastRevision: "2026-10-28",
  },
  {
    id: "s13",
    city: "Salt Lake City, UT",
    venueName: "Delta Center",
    date: "2027-04-01",
    fidelity: "SEED",
    sourceScore: 24,
    riggingStatus: "NOT_STARTED",
    logisticsStatus: "PENDING",
    lastRevision: "2026-10-26",
  },
  {
    id: "s14",
    city: "Phoenix, AZ",
    venueName: "Footprint Center",
    date: "2027-04-03",
    fidelity: "SEED",
    sourceScore: 30,
    riggingStatus: "NOT_STARTED",
    logisticsStatus: "PENDING",
    lastRevision: "2026-10-24",
  },
  {
    id: "s15",
    city: "Los Angeles, CA",
    venueName: "Crypto.com Arena",
    date: "2027-04-06",
    fidelity: "SEED",
    sourceScore: 48,
    riggingStatus: "NOT_STARTED",
    logisticsStatus: "PENDING",
    lastRevision: "2026-10-20",
  },
  {
    id: "s16",
    city: "San Francisco, CA",
    venueName: "Chase Center",
    date: "2027-04-09",
    fidelity: "SEED",
    sourceScore: 42,
    riggingStatus: "NOT_STARTED",
    logisticsStatus: "PENDING",
    lastRevision: "2026-10-18",
  },
  {
    id: "s17",
    city: "Portland, OR",
    venueName: "Moda Center",
    date: "2027-04-11",
    fidelity: "SEED",
    sourceScore: 28,
    riggingStatus: "NOT_STARTED",
    logisticsStatus: "PENDING",
    lastRevision: "2026-10-15",
  },
  {
    id: "s18",
    city: "Seattle, WA",
    venueName: "Climate Pledge Arena",
    date: "2027-04-13",
    fidelity: "SEED",
    sourceScore: 34,
    riggingStatus: "NOT_STARTED",
    logisticsStatus: "PENDING",
    lastRevision: "2026-10-14",
  },
  {
    id: "s19",
    city: "Minneapolis, MN",
    venueName: "Target Center",
    date: "2027-04-16",
    fidelity: "SEED",
    sourceScore: 26,
    riggingStatus: "NOT_STARTED",
    logisticsStatus: "PENDING",
    lastRevision: "2026-10-10",
  },
];
