/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenuesSpectrumCenterRouteImport } from './routes/venues.spectrum-center'
import { Route as VenuesBokCenterRouteImport } from './routes/venues.bok-center'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesSpectrumCenterRoute = VenuesSpectrumCenterRouteImport.update({
  id: '/venues/spectrum-center',
  path: '/venues/spectrum-center',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesBokCenterRoute = VenuesBokCenterRouteImport.update({
  id: '/venues/bok-center',
  path: '/venues/bok-center',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/venues/bok-center': typeof VenuesBokCenterRoute
  '/venues/spectrum-center': typeof VenuesSpectrumCenterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/venues/bok-center': typeof VenuesBokCenterRoute
  '/venues/spectrum-center': typeof VenuesSpectrumCenterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/venues/bok-center': typeof VenuesBokCenterRoute
  '/venues/spectrum-center': typeof VenuesSpectrumCenterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/venues/bok-center' | '/venues/spectrum-center'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/venues/bok-center' | '/venues/spectrum-center'
  id: '__root__' | '/' | '/venues/bok-center' | '/venues/spectrum-center'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VenuesBokCenterRoute: typeof VenuesBokCenterRoute
  VenuesSpectrumCenterRoute: typeof VenuesSpectrumCenterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/spectrum-center': {
      id: '/venues/spectrum-center'
      path: '/venues/spectrum-center'
      fullPath: '/venues/spectrum-center'
      preLoaderRoute: typeof VenuesSpectrumCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/bok-center': {
      id: '/venues/bok-center'
      path: '/venues/bok-center'
      fullPath: '/venues/bok-center'
      preLoaderRoute: typeof VenuesBokCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VenuesBokCenterRoute: VenuesBokCenterRoute,
  VenuesSpectrumCenterRoute: VenuesSpectrumCenterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
